url: https://sakarias.net
# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
baseurl: /
title: Sakarias Gaming
author: Sakarias
description:
avatar: sakarias.webp
email: sakarias@sakarias.net
#github: biomadeira/sustain # username
twitter: sakariasgaming
twitch: sakarias
youtube: sakarias
instagram: sakariasgaming
reddit: sakarias
#facebook:
#linkedin: username
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-57646-11


# needed for travis-ci build
exclude: [vendor]
